# Numpy

In [2]:
import numpy as np

## Creating Array

In [ ]:
#1D array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#2D array
b =np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
# A 3D array has three dimensions: (depth, rows, columns)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
#dtype
np.array([1,2,3,0],dtype=float)

array([1., 2., 3., 0.])

In [23]:
# np.arange(): create an array with evenly spaced values within a range
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [25]:
# np.reshape(): change the shape of a NumPy array without changing its data
np.arange(1,11).reshape(5,2)



array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
# np.ones(): create a NumPy array filled with 1s
# np.zeros(): create a NumPy array filled with 0s
np.ones((2,3))
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# np.random.random((2,3)): create a 2x3 array with random floats between 0 and 1
np.random.random((2,3))

array([[0.74744561, 0.42496394, 0.20209767],
       [0.02626507, 0.87386631, 0.88821569]])

In [35]:
# np.linspace(): create an array of evenly spaced numbers over a specified interval
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [36]:
# np.identity(n): create an n x n identity matrix (1s on the diagonal, 0s elsewhere)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [43]:
# .ndim: returns the number of dimensions (axes) of a NumPy array
a1.ndim

1

In [50]:
# .shape: returns the dimensions (rows, columns, etc.) of a NumPy array as a tuple
a2.shape

(3, 4)

In [52]:
# .size: returns the total number of elements in a NumPy array
a3.size

8

In [55]:
# .itemsize: returns the size (in bytes) of each element in a NumPy array
a1.itemsize

8

In [ ]:
a1.dtype

dtype('int64')

#### Changing Datatype

In [57]:
a1.astype(np.int16)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

## Array Operation

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [64]:
# scalar operations

a2+3

array([[15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [67]:
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Fuctions

In [76]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[96.,  5., 12.],
       [96.,  7., 81.],
       [ 3., 84., 13.]])

In [82]:
#max/min/sum/prod
# np.max(): returns the largest value in the array
# np.min(): returns the smallest value in the array
# np.sum(): returns the sum of all elements (or along a specific axis)
# np.prod(): returns the product of all elements (or along a specific axis)

#axis=0 ->  Column-wise 
#axis=1 ->  Row-wise  
np.prod(a1,axis=0)


array([27648.,  2940., 12636.])

In [84]:
# np.mean(): returns the average value of the array
# np.median(): returns the middle value of the array
# np.std(): returns the standard deviation (spread of data)
# np.var(): returns the variance (average of squared deviations)

np.mean(a1,axis=1)

array([37.66666667, 61.33333333, 33.33333333])

In [92]:
np.sin(a1)

array([[ 0.98358775, -0.95892427, -0.53657292],
       [ 0.98358775,  0.6569866 , -0.62988799],
       [ 0.14112001,  0.73319032,  0.42016704]])

In [ ]:
# dot product
np.dot(a1,a2)

array([[1472., 1585., 1698., 1811.],
       [2884., 3068., 3252., 3436.],
       [1640., 1740., 1840., 1940.]])

In [95]:
# log and exponents
np.exp(a1)

array([[4.92345829e+41, 1.48413159e+02, 1.62754791e+05],
       [4.92345829e+41, 1.09663316e+03, 1.50609731e+35],
       [2.00855369e+01, 3.02507732e+36, 4.42413392e+05]])

In [ ]:
# round/floor/ceil
# np.round(): round values to the nearest integer (or given decimals)
# np.floor(): round values down to the nearest integer
# np.ceil(): round values up to the nearest integer


np.round(np.random.random((2,3))*100)

array([[24., 71., 72.],
       [63., 24., 90.]])

## Indexing and Slicing

In [99]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [100]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a1[-2]

np.int64(8)

In [113]:
a2[1,2]

np.int64(6)

In [ ]:
a3[1,0,1] #D,R,C

np.int64(5)

In [124]:
a1[2:7:2]     #start : stop : increment

array([2, 4, 6])

In [131]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2] #.  select all rows but only the 3rd column (index 2)

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3] #.  select rows from index 1 onward and columns 1 to 2

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[::2,::3] #. take every 2nd row and every 3rd column

array([[ 0,  3],
       [ 8, 11]])

In [148]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [158]:
a2[1,::3]

array([4, 7])

In [161]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [164]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [173]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [178]:
a3[0,1]

array([3, 4, 5])

In [180]:
a3[1,:,1]

array([10, 13, 16])

In [182]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0::2,0,::2] #.   keeps second axis as a slice → output remains 3D

array([[ 0,  2],
       [18, 20]])

## Iterating

In [200]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [201]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:     #print row wise
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [196]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:    # print 2D wise
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# np.nditer(): efficient multi-dimensional iterator to loop over all elements of an array

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshape


In [210]:
# Transpose
print(a2)
np.transpose(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a3.T # transpose

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
#ravel -> convert nD to 1D 
a3.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [226]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


In [219]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [220]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [222]:
# Horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [227]:
# Vertical stacking 
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [239]:
# Horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [236]:
# Vertical splitting
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]