In [3]:
import numpy as np 
a = np.random.randint(1,100,15)
a

array([19, 86, 42, 88, 93, 57, 14, 43, 54, 66,  3, 25, 60, 38, 82])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[96, 11, 51, 19],
       [97, 15, 98, 60],
       [83, 82, 10, 18],
       [30, 81, 56, 19],
       [60, 35,  9, 74],
       [97, 64, 63,  2]])

In [5]:
np.sort(a)[::-1]

array([93, 88, 86, 82, 66, 60, 57, 54, 43, 42, 38, 25, 19, 14,  3])

In [6]:
np.sort(b,axis=0)

array([[30, 11,  9,  2],
       [60, 15, 10, 18],
       [83, 35, 51, 19],
       [96, 64, 56, 19],
       [97, 81, 63, 60],
       [97, 82, 98, 74]])

In [7]:
np.append(a,200)

array([ 19,  86,  42,  88,  93,  57,  14,  43,  54,  66,   3,  25,  60,
        38,  82, 200])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[96., 11., 51., 19.,  1.],
       [97., 15., 98., 60.,  1.],
       [83., 82., 10., 18.,  1.],
       [30., 81., 56., 19.,  1.],
       [60., 35.,  9., 74.,  1.],
       [97., 64., 63.,  2.,  1.]])

In [9]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [11]:
a = np.array([1,1,2,2,4,5,12,5,21,4,8,4])
np.unique(a)

array([ 1,  2,  4,  5,  8, 12, 21])

In [12]:
np.expand_dims(a,axis=1) # convert 1D to 2D

array([[ 1],
       [ 1],
       [ 2],
       [ 2],
       [ 4],
       [ 5],
       [12],
       [ 5],
       [21],
       [ 4],
       [ 8],
       [ 4]])

In [13]:
np.where(a>5)

(array([ 6,  8, 10]),)

In [14]:
# Replace all values > 5 with 0
# np,where(condition,true,false)
np.where(a>5,0,a)

array([1, 1, 2, 2, 4, 5, 0, 5, 0, 4, 0, 4])

In [15]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[67, 16, 33, 47],
       [93, 10, 25,  9],
       [64, 95, 74, 64],
       [24, 40, 98, 93],
       [73, 80, 35, 24],
       [26,  1, 60, 72]])

In [16]:
np.argmax(a)

np.int64(8)

In [17]:
np.argmax(b,axis=0)

array([1, 2, 3, 3])

In [18]:
np.argmax(b,axis=1)

array([0, 0, 1, 2, 1, 3])

In [19]:
np.argmin(b)

np.int64(21)

In [20]:
np.cumsum(a)

array([ 1,  2,  4,  6, 10, 15, 27, 32, 53, 57, 65, 69])

In [21]:
np.cumsum(b)

array([  67,   83,  116,  163,  256,  266,  291,  300,  364,  459,  533,
        597,  621,  661,  759,  852,  925, 1005, 1040, 1064, 1090, 1091,
       1151, 1223])

In [22]:
np.cumsum(b,axis=0)

array([[ 67,  16,  33,  47],
       [160,  26,  58,  56],
       [224, 121, 132, 120],
       [248, 161, 230, 213],
       [321, 241, 265, 237],
       [347, 242, 325, 309]])

In [23]:
np.cumprod(a)

array([       1,        1,        2,        4,       16,       80,
            960,     4800,   100800,   403200,  3225600, 12902400])

In [24]:
np.cumprod(b)

array([                  67,                 1072,                35376,
                    1662672,            154628496,           1546284960,
                38657124000,         347914116000,       22266503424000,
           2115317825280000,   156533519070720000, -8428598853183471616,
         627812334401748992,  6665749302360408064,  7607389051485683712,
        6510906987205623808, -4319135850437804032,  4957269365457158144,
        7483731127614570496, -4857893674345824256,  2821972982975430656,
        2821972982975430656,  3297682315139874816, -2374546268153184256])

In [25]:
np.percentile(a,60)

np.float64(4.6)

In [26]:
np.median(a)

np.float64(4.0)

#### np.histogram

In [28]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70])

(array([10,  1,  1,  0,  0,  0,  0]), array([ 0, 10, 20, 30, 40, 50, 60, 70]))

#### np.corrcoef
- Return Pearson product-moment correlation coefficieants

In [38]:
salary = np.array([20000,40000,25000,30000,50000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25492496],
       [0.25492496, 1.        ]])

#### np.isin()
- checks whether each element of an array is present in another array


In [65]:
x=np.array([1,2,3,4,5,6,76,7,43,1,45])
y=np.array([34,6,2,765,2,76,2,3,5,6,4])
x[np.isin(x,y)]

array([ 2,  3,  4,  5,  6, 76])

####  np.flip()
 * reverses the order of elements along a given axis

In [46]:
np.flip(x)

array([45,  1, 43,  7, 76,  6,  5,  4,  3,  2,  1])

#### np.put()
- places values into an array at specific indices


In [ ]:
x[np.put(x,[1],[0])] # index 1 value 20 is updated to 0


array([[ 1,  0,  3,  4,  5,  6, 76,  7, 43,  1, 45]])

#### np.delete()
- removes elements, rows, or columns from an array


In [53]:
np.delete(x,[1,3])

array([ 1,  3,  5,  6, 76,  7, 43,  1, 45])

### Set Functions


In [54]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
np.intersect1d(m,n)

array([3, 4, 5])

In [57]:
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
np.setxor1d(m,n) #remove commen values

array([1, 2, 6, 7])

In [ ]:
# np.in1d(): checks whether each element of an array is present in another array
m[np.in1d(m,1)]

/var/folders/1t/qqtm35950b74y6zwph6yt5vm0000gn/T/ipykernel_52473/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

#### np.clip()
- limits (clips) the values in an array to a given range.<br>
`syntax:`<br>
     &nbsp;&nbsp;&nbsp;` np.clip(array, min_value, max_value)`


In [73]:
np.clip(x,5,45)

array([ 5,  5,  5,  5,  5,  6, 45,  7, 43,  5, 45])

In [74]:
x

array([ 1,  2,  3,  4,  5,  6, 76,  7, 43,  1, 45])