In [3]:
import numpy as np 
a = np.random.randint(1,100,15)
a

array([86, 55, 53, 38,  1, 37, 11, 54, 28, 20, 40, 75, 96, 87, 44])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[96, 55, 31, 37],
       [ 1, 24, 49, 13],
       [37, 17, 79, 12],
       [21, 34, 80, 68],
       [72, 82, 53, 73],
       [74, 28, 35, 74]])

In [14]:
np.sort(a)[::-1]

array([96, 87, 86, 75, 55, 54, 53, 44, 40, 38, 37, 28, 20, 11,  1])

In [10]:
np.sort(b,axis=0)

array([[ 1, 17, 31, 12],
       [21, 24, 35, 13],
       [37, 28, 49, 37],
       [72, 34, 53, 68],
       [74, 55, 79, 73],
       [96, 82, 80, 74]])

In [15]:
np.append(a,200)

array([ 86,  55,  53,  38,   1,  37,  11,  54,  28,  20,  40,  75,  96,
        87,  44, 200])

In [20]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[96., 55., 31., 37.,  1.],
       [ 1., 24., 49., 13.,  1.],
       [37., 17., 79., 12.,  1.],
       [21., 34., 80., 68.,  1.],
       [72., 82., 53., 73.,  1.],
       [74., 28., 35., 74.,  1.]])

In [21]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [25]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [43]:
a = np.array([1,1,2,2,4,5,12,5,21,4,8,4])
np.unique(a)

array([ 1,  2,  4,  5,  8, 12, 21])

In [44]:
np.expand_dims(a,axis=1) # convert 1D to 2D

array([[ 1],
       [ 1],
       [ 2],
       [ 2],
       [ 4],
       [ 5],
       [12],
       [ 5],
       [21],
       [ 4],
       [ 8],
       [ 4]])

In [45]:
np.where(a>5)

(array([ 6,  8, 10]),)

In [46]:
# Replace all values > 5 with 0
# np,where(condition,true,false)
np.where(a>5,0,a)

array([1, 1, 2, 2, 4, 5, 0, 5, 0, 4, 0, 4])

In [40]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[29, 75, 17, 60],
       [50,  8,  9, 75],
       [26, 94,  6,  9],
       [49, 21, 69, 48],
       [22, 73, 61, 55],
       [ 8, 10, 28,  6]])

In [47]:
np.argmax(a)

np.int64(8)

In [48]:
np.argmax(b,axis=0)

array([1, 2, 3, 1])

In [49]:
np.argmax(b,axis=1)

array([1, 3, 1, 2, 1, 2])

In [51]:
np.argmin(b)

np.int64(10)

In [52]:
np.cumsum(a)

array([ 1,  2,  4,  6, 10, 15, 27, 32, 53, 57, 65, 69])

In [53]:
np.cumsum(b)

array([ 29, 104, 121, 181, 231, 239, 248, 323, 349, 443, 449, 458, 507,
       528, 597, 645, 667, 740, 801, 856, 864, 874, 902, 908])

In [57]:
np.cumsum(b,axis=0)

array([[ 29,  75,  17,  60],
       [ 79,  83,  26, 135],
       [105, 177,  32, 144],
       [154, 198, 101, 192],
       [176, 271, 162, 247],
       [184, 281, 190, 253]])

In [54]:
np.cumprod(a)

array([       1,        1,        2,        4,       16,       80,
            960,     4800,   100800,   403200,  3225600, 12902400])

In [58]:
np.cumprod(b)

array([                  29,                 2175,                36975,
                    2218500,            110925000,            887400000,
                 7986600000,         598995000000,       15573870000000,
           1463943780000000,     8783662680000000,    79052964120000000,
        3873595241880000000,  7558523784641793536,  5029307076416308736,
        1599066709758648320, -1714020532728840192,  4003709626761527296,
        4418614274228994048,  3216112124370501632,  7282152921254461440,
        -965447082293592064, -8585774230511026176,  3825586838062497792])

In [69]:
np.percentile(a,60)

np.float64(4.6)

In [70]:
np.median(a)

np.float64(4.0)

#### np.histogram